import { pgTable, uuid, text, timestamp, integer, jsonb } from 'drizzle-orm/pg-core';

// User table with auth and role support
export const user = pgTable('user', {
	id: text('id').primaryKey(), // UUID generated by Lucia or your auth flow

	email: text('email').notNull().unique(),
	hashedPassword: text('hashed_password').notNull(), // hashed_password is the DB column, but use camelCase in code

	role: text('role').notNull().default('free'), // Options: 'free', 'premium', 'admin', etc.

	createdAt: timestamp('created_at', {
		withTimezone: true,
		mode: 'date'
	}).defaultNow()
});

// Session table for Lucia session tracking
export const session = pgTable('session', {
	id: text('id').primaryKey(),

	userId: text('user_id')
		.notNull()
		.references(() => user.id),

	expiresAt: timestamp('expires_at', {
		withTimezone: true,
		mode: 'date'
	}).notNull()
});

// EVENTS
export const event = pgTable('event', {
	id: text('id').primaryKey(), // if you want human slugs like 'fall-fest-2025'
	title: text('title').notNull(),
	paddlePriceId: text('paddle_price_id').notNull(),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// TICKETS
export const ticket = pgTable('ticket', {
	id: uuid('id').defaultRandom().primaryKey(), // <-- uuid + defaultRandom
	userId: text('user_id'),
	eventId: text('event_id').notNull(),
	code: text('code').notNull(),
	quantity: integer('quantity').default(1),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow(),
	voidedAt: timestamp('voided_at', { withTimezone: true, mode: 'date' })
});

// ENTITLEMENTS (for the simple Paddle product/courses)
export const entitlement = pgTable('entitlement', {
	id: uuid('id').defaultRandom().primaryKey(), // <-- uuid + defaultRandom
	userId: text('user_id'),
	product: text('product').notNull(),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// ORDERS (audit)
export const order = pgTable('order', {
	id: uuid('id').defaultRandom().primaryKey(), // <-- uuid + defaultRandom
	provider: text('provider').notNull(), // 'paddle' | 'authnet'
	providerRef: text('provider_ref').notNull(),
	userEmail: text('user_email'),
	amount: text('amount'),
	currency: text('currency'),
	meta: jsonb('meta'),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// WEBHOOK IDEMPOTENCY
export const webhookEvent = pgTable('webhook_event', {
	id: text('id').primaryKey(), // Paddle/Auth.Net event id as text (no default)
	provider: text('provider').notNull(),
	receivedAt: timestamp('received_at', { withTimezone: true, mode: 'date' }).defaultNow()
});
