import { pgTable, uuid, text, timestamp, integer, jsonb, boolean, decimal } from 'drizzle-orm/pg-core';

// User table with auth and role support
export const user = pgTable('user', {
	id: text('id').primaryKey(), // UUID generated by Lucia or your auth flow

	email: text('email').notNull().unique(),
	hashedPassword: text('hashed_password').notNull(), // hashed_password is the DB column, but use camelCase in code

	// User profile
	firstName: text('first_name').notNull(),
	lastName: text('last_name').notNull(),
	gemId: text('gem_id'), // Optional GEM ID for tournament registration

	role: text('role').notNull().default('free'), // Options: 'free', 'premium', 'admin', 'writer', 'tournament_staff'

	// Subscription tracking
	subscriptionId: text('subscription_id'), // Authorize.net subscription ID for premium users

	// User preferences
	theme: text('theme').default('dark'), // Site is permanently in dark mode

	createdAt: timestamp('created_at', {
		withTimezone: true,
		mode: 'date'
	}).defaultNow()
});

// Session table for Lucia session tracking
export const session = pgTable('session', {
	id: text('id').primaryKey(),

	userId: text('user_id')
		.notNull()
		.references(() => user.id),

	expiresAt: timestamp('expires_at', {
		withTimezone: true,
		mode: 'date'
	}).notNull()
});

// EVENTS
export const event = pgTable('event', {
	id: text('id').primaryKey(), // UUID or slug
	title: text('title').notNull(),
	location: text('location'), // Nullable for migration compatibility
	price: decimal('price', { precision: 10, scale: 2 }).notNull(),
	format: text('format'), // e.g., "Standard", "Modern", "Draft" - nullable for migration
	gemIdRequired: boolean('gem_id_required').default(false),
	circuit: text('circuit'), // e.g., "Los Angeles", "New England"
	eventDate: timestamp('event_date', { withTimezone: true, mode: 'date' }), // Nullable for migration
	description: text('description'),
	premiumDiscount: boolean('premium_discount').default(false), // 10% discount for premium users
	createdBy: text('created_by').references(() => user.id),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// TICKETS
export const ticket = pgTable('ticket', {
	id: uuid('id').defaultRandom().primaryKey(),
	userId: text('user_id').references(() => user.id),
	eventId: text('event_id').notNull().references(() => event.id),
	code: text('code').notNull(),
	quantity: integer('quantity').default(1),

	// Player information
	firstName: text('first_name'), // Player's first name
	lastName: text('last_name'), // Player's last name
	gemId: text('gem_id'), // Gem ID if required by event

	// Payment information
	amountPaid: decimal('amount_paid', { precision: 10, scale: 2 }), // Actual amount paid (with discount if applicable)
	transactionId: text('transaction_id'), // Authorize.net transaction ID

	// Status tracking
	refunded: boolean('refunded').default(false),
	refundedAt: timestamp('refunded_at', { withTimezone: true, mode: 'date' }),
	enteredIntoGem: boolean('entered_into_gem').default(false), // Whether player has been entered into tournament software

	// Timestamps
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow(),
	voidedAt: timestamp('voided_at', { withTimezone: true, mode: 'date' })
});

// ENTITLEMENTS (for courses and digital products)
export const entitlement = pgTable('entitlement', {
	id: uuid('id').defaultRandom().primaryKey(), // <-- uuid + defaultRandom
	userId: text('user_id'),
	product: text('product').notNull(),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// ORDERS (audit)
export const order = pgTable('order', {
	id: uuid('id').defaultRandom().primaryKey(), // <-- uuid + defaultRandom
	provider: text('provider').notNull(), // 'authnet'
	providerRef: text('provider_ref').notNull(),
	userEmail: text('user_email'),
	amount: text('amount'),
	currency: text('currency'),
	meta: jsonb('meta'),
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// WEBHOOK IDEMPOTENCY
export const webhookEvent = pgTable('webhook_event', {
	id: text('id').primaryKey(), // Auth.Net event id as text (no default)
	provider: text('provider').notNull(),
	receivedAt: timestamp('received_at', { withTimezone: true, mode: 'date' }).defaultNow()
});

// EVENT STAFF ASSIGNMENTS (for tournament staff)
export const eventStaff = pgTable('event_staff', {
	id: uuid('id').defaultRandom().primaryKey(),
	userId: text('user_id').notNull().references(() => user.id),
	eventId: text('event_id').notNull().references(() => event.id),
	assignedBy: text('assigned_by').references(() => user.id), // Admin who assigned the staff
	createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow()
});
